name: $(Build.Repository.Name)-$(Build.SourceBranchName)

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md
    include:
      - envs/dev/*
      - pipelines/pipeline-dev.yml

pool: Azure Pipelines

resources:
  repositories:
    - repository: PipelineTemplates
      type: github
      name: przemekgorzynski/PipelineTemplates

parameters:
  - name: action
    displayName: Action
    type: string
    default: 'Plan'
    values:
    - Plan
    - Apply
    - Destroy

variables:
  - name: ServiceConnection
    value: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    readonly: true
  - name: TargetSubscriptionID
    value: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    readonly: true
  - name: env
    value: dev
    readonly: true
  
stages:
  - stage: Terraform_scan
    dependsOn: []
    jobs:
      - job: TFsec
        steps:
          - template: Azure_DevOps/security/terraform_scan.yml@PipelineTemplates
            parameters:
              ServiceConnection: ${{ variables.ServiceConnection }}
  - stage: Install_Terragrunt
    dependsOn: [Terraform_scan]
    jobs:
      - job: Terragrunt_Installation
        steps:
          - template: Azure_DevOps/terragrunt/install.yml@PipelineTemplates
  - stage: Plan
    condition: eq('${{ parameters.Action }}', 'Plan')
    dependsOn: [Install_Terragrunt]
    jobs:
      - job: Plan
        timeoutInMinutes: 20
        steps:
          - template: Azure_DevOps/terragrunt/init.yml@PipelineTemplates
            parameters:
              env: ${{ variables.env }}
              ServiceConnection: ${{ variables.ServiceConnection }}
              TargetSubscriptionID: ${{ variables.TargetSubscriptionID }}
          - template: Azure_DevOps/terragrunt/plan.yml@PipelineTemplates
            parameters:
              env: ${{ variables.env }}
              ServiceConnection: ${{ variables.ServiceConnection }}
              TargetSubscriptionID: ${{ variables.TargetSubscriptionID }}
  - stage: Apply
    condition: eq('${{ parameters.Action }}', 'Apply')
    dependsOn: [Install_Terragrunt]
    jobs:
      - job: Apply
        steps:
          - template: Azure_DevOps/terragrunt/init.yml@PipelineTemplates
            parameters:
              env: ${{ variables.env }}
              ServiceConnection: ${{ variables.ServiceConnection }}
              TargetSubscriptionID: ${{ variables.TargetSubscriptionID }}
          - template: Azure_DevOps/terragrunt/plan.yml@PipelineTemplates
            parameters:
              env: ${{ variables.env }}
              ServiceConnection: ${{ variables.ServiceConnection }}
              TargetSubscriptionID: ${{ variables.TargetSubscriptionID }}
          - template: Azure_DevOps/terragrunt/apply.yml@PipelineTemplates
            parameters:
              env: ${{ variables.env }}
              ServiceConnection: ${{ variables.ServiceConnection }}
              TargetSubscriptionID: ${{ variables.TargetSubscriptionID }}
  - stage: Destroy
    condition: eq('${{ parameters.Action }}', 'Destroy')
    dependsOn: [Install_Terragrunt]
    jobs:
      - job: Destroy
        steps:
          - template: Azure_DevOps/terragrunt/init.yml@PipelineTemplates
            parameters:
              env: ${{ variables.env }}
              ServiceConnection: ${{ variables.ServiceConnection }}
              TargetSubscriptionID: ${{ variables.TargetSubscriptionID }}
          - template: Azure_DevOps/terragrunt/destroy.yml@PipelineTemplates
            parameters:
              env: ${{ variables.env }}
              ServiceConnection: ${{ variables.ServiceConnection }}
              TargetSubscriptionID: ${{ variables.TargetSubscriptionID }}              
