name: Dev
run-name: Runned ${{ github.ref }} branch by @${{ github.actor }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

runs-on: ubuntu-latest

jobs:
  Installation:
    steps:
      - uses: hashicorp/setup-terraform@v2
        name: Install Terraform
      - name: Install Checkov
        run: |
          pip3 install checkov
      - name: Install Terragrunt
        run: |
          wget -O /tmp/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.45.8/terragrunt_linux_amd64
          chmod +x /tmp/terragrunt && sudo mv /tmp/terragrunt /usr/local/bin/terragrunt
  Validation:
    needs: Installation
    steps:
      - uses: actions/checkout@v3
      - name: Tfsec scan
        uses: triat/terraform-security-scan@v3.0.3
      - name: Run Tests
        working-directory: ./terraform
        run: |
          terraform init -backend=false
          terraform validate
          checkov -d . --framework terraform --download-external-modules true
