name: Dev

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Scan_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        name: Install Terraform
      - name: Install Tfsec
        uses: triat/terraform-security-scan@v3.0.3
      - name: Install Checkov
        run: |
          pip3 install checkov
